apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: test-argo
    run: rok-kafka
  name: rok-kafka
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: test-argo
    run: rok-kafka
  type: NodePort
status:
  loadBalancer: {}
