apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: rok-kafka
  name: rok-kafka
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 34200
  selector:
    run: rok-kafka
  type: NodePort
status:
  loadBalancer: {}
