apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rok-kafka
  name: rok-kafka
spec:
  containers:
  - image: www.auction-price.co.kr/kafka/kafkarok:v1
    name: rok-kafka
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
